- name: users | draymond | remove preinstalled clutter from home directory
  file:
    path: /home/draymond/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | draymond | create personal config directories
  tags: dotfiles,dotfiles-draymond
  file:
    path: /home/draymond/{{ item.dir }}
    state: directory
    owner: draymond
    group: draymond
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: pictures }
    - { dir: projects }
    - { dir: templates }

- name: users | draymond | copy user-dirs.dirs
  tags: dotfiles,dotfiles-draymond
  copy:
    src: users/draymond/user-dirs.dirs
    dest: /home/draymond/.config/user-dirs.dirs
    owner: draymond
    group: draymond
    mode: 0600
  notify: update_xdg

- name: users | draymond | copy personal config files
  tags: dotfiles,dotfiles-draymond
  copy:
    src: users/draymond/{{ item.src }}
    dest: /home/draymond/{{ item.dest }}
    owner: draymond
    group: draymond
    mode: 0600
  with_items:
    - { src: 'asunder', dest: '.asunder' }
    - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
    - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
    - { src: 'gvimrc', dest: '.gvimrc' }
    - { src: 'linode-cli', dest: '.config/linode-cli' }
    - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

#- name: users | draymond | copy profile image
#  tags: dotfiles,dotfiles-draymond
#  copy:
#    src: users/draymond/profile_image.png
#    dest: /var/lib/AccountsService/icons/draymond.png
#    owner: root
#    group: root
#    mode: 0644
#